# This workflow will run a test suite.

name: Tests
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  call-linting:
    uses: voightp/github-actions/.github/workflows/run-linting.yml@master
    with:
      os: ubuntu-latest
      python-version: 3.9
  call-tests:
    needs: call-linting
    uses: voightp/github-actions/.github/workflows/run-tests.yml@master
    with:
      pytest-args: "tests -v"
